### ISSUE TITLE
Clarify how development dependencies are installed

### ISSUE THREAD

**Issue by cjolowicz** [cjolowicz/nox-poetry#399]
There's sometimes confusion why `session.install` does not get the development dependencies installed. The documentation could be clearer here.

**Comment by cjolowicz** [comment]
See #389

**Comment by matteosantama** [comment]
Is it possible to install the dev dependencies as well? Or is it a design choice to disallow it?

**Comment by matteosantama** [comment]
The reason I ask is I have a session that runs `mypy`. With `mypy>=0.900`, you must explicitly install type-stubs as [dependencies](http://mypy-lang.blogspot.com/2021/06/mypy-0900-released.html). The easiest way to manage this (I think) would be to add each of the type-stubs as a dev dependency of my library, and then install all the dev dependencies in the `nox` session.

**Comment by cjolowicz** [comment]
You can do this:

```python
session.install("mypy", "types-foobar")
```

Or this:

```python
session.run_always("poetry", "install", external=True)
```

`session.install` has no concept of development dependencies, because it is a front-end to `pip install`.

nox-poetry does not change that. It just makes it respect the lockfile. So if you add mypy and types-foobar as development dependencies, the first example will install them at the versions recorded in the lockfile.

This is by design. Nox sessions are for isolated, repeatable, dedicated checks. That's what makes them different from a development environment like the one Poetry sets up for you, where you do want everything installed for convenience (and an editable install of your own package, so you see changes immediately).

**Comment by cjolowicz** [comment]
To expand on this, `session.install(".")` installs your package and its dependencies, but not development dependencies. That's because the development dependencies are not a part of your package metadata. They're a Poetry-specific extension.

So you need to install these dependencies explicitly: `session.install("mypy", ...)`.

nox-poetry is very much about development dependencies. It makes sure that you can manage these tools in Poetry, and the Nox sessions will use the expected version.

If you really want to install every development dependency in a Nox session, just use Poetry as an external command, as shown above in the second example.

**Comment by matteosantama** [comment]
Got it, thanks!

**Comment by kentmartin73** [comment]
That's good to know - so not an ideal solution.  Perhaps nox-poetry could provide `session.requirements_file` to allow it to keep working?

There's no hugely compelling reasoning.  This makes pip install everything, instead of a mix of pip when you use `session.install` and poetry when you use `session.run_always("poetry", blah)`

Why does nox provide `session.install` at all when you could just use `session.run_always("pip", "install", "foo", external=True)`?  I guess by not calling pip externally, nox can make changes to the install logic if they want to without noxfiles being changed - although calling `session.install` with `--some-pip-flag` rather limits this possibility.

What might be nice as an alternative/addition is if nox-poetry provided a `session.poetry_install` in a similar vein to `session.conda_install` which nox provides, then, we get to choose which install tool to use to install (`install` for pip, `conda_install` for Conda and `poetry_install` for Poetry)
