### ISSUE TITLE
Warn/Raise if trying to install a package not specified as a dependency

### ISSUE THREAD

**Issue by alexifm** [cjolowicz/nox-poetry#439]
We wrote a noxfile which has a session that installs dev dependencies that were accidentally not specified in the pyproject file.  It got me thinking that a warning or an error if we were trying to do that might be a nice feature for non-poetry.  I'm not totally sure how that would be detected efficiently though.

**Comment by cjolowicz** [comment]
This used to be `nox-poetry` behavior when requirements were still exported with hashes. Unfortunately, this is no longer possible because pip dropped support for hashes in constraints files, see #222. To be frank, I'm hesitant to introduce logic in `nox-poetry` to handle this, as I prefer to keep this package restricted to the minimal glue code for Poetry and Nox. (To be precise, the minimal glue code required to get pinned installations of subsets of development dependencies.) I'm open for suggestions though how this could be achieved.
