### ISSUE TITLE
[Question] libraries with uncommitted lockfile

### ISSUE THREAD

**Issue by danieleades** [cjolowicz/nox-poetry#555]
quick question-

the conventional wisdom is that the lockfile is committed for binaries, and not committed for libraries. Tests in CI are not necessarily reproducible without the lockfile, but then again since the lockfile is not respected when using a library as a dependency *anyway* then this is closer to the deployment environment.

In light of the above, how should `nox-poetry` be used with a library that would otherwise not commit the lockfile to VCS at all?

**Comment by cjolowicz** [comment]
The line between applications and libraries is much less clear in Python than in some other languages like C or C++. Even if you accept this dichotomy, reproducible deployments are not the only reason to commit lockfiles. Generally, I think that the advantages of committing lockfiles outweigh the disadvantages, at least for the Python packages I have seen. This puts every developer on the same page, and gives them reproducible checks, both locally and in CI.

If you need to test against different versions of an important dependency, I recommend to use `@nox.parametrize`  to specify those versions, and install that dependency on top of your pinned dependencies. See our earlier discussion here:  https://github.com/cjolowicz/nox-poetry/issues/268#issuecomment-774549874

It is true though that running checks with pinned dependencies *can* mean that you're testing against a different set of dependencies than the one your users get if they `pip install` your package. This can happen even if all your dependencies are "up to date". The reason is that the core package dependencies need to be resolved together with the development dependencies. So your development dependencies can "hold back" some of the (direct or indirect) core dependencies. Your users don't see those development dependencies, so they may get more recent packages in their environments. See https://github.com/cjolowicz/cookiecutter-hypermodern-python/issues/817 for an earlier discussion. This can be valid reason to test without pinning, although I would do this as an *additional* check if it proves to be a problem.

**Comment by danieleades** [comment]
thanks @cjolowicz, I appreciate you taking the time.
